### PR TITLE
fix/improve show and new otherData get/set functions

### PR DESCRIPTION
**Pull request by lgatto**
- fix: show filenames based on length, not null
- feat: show qdata and otherdata slots
- feat: new otherData and otherData<- functions

### CODE REVIEW

**Comment by lgatto** [comment]
These changes/fixes have come up through the [indexing work](https://uclouvain-cbio.github.io/sager/articles/sager.html#combining-raw-quantitation-and-identification-data) I am doing with MsExperiment objects.

**Review by jorainer — CHANGES_REQUESTED** [review]
Thanks @lgatto for the PR. Code looks good, but can you please also add unit tests for the new function (and eventually the updated `show` method)?

**Comment by lgatto** [comment]
PR updated with tests.

**Review by jorainer — APPROVED** [review]
Thanks Laurent!

**Comment by lgatto** [comment]
Pushed to bioc.

**Pull request merged**
